version: '3'

services:
  app:
    #fpm
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: dbname
      DB_USERNAME: username
      DB_PASSWORD: p455w0rd
      DB_CONNECTION: mysql
    expose:
      - 9000
  web:
    #nginx
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    ports:
      - 80:80
      - 443:443
  database:
    #database
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: wh00pwh00p
    ports:
      - "3306:3306"
volumes:
  dbdata:
