version: '3'

services:
  app:
    #fpm
    image: shakyshane/laravel-app
    volumes:
      - /var/www/storage
    env_file: '.env'
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: dbname
      DB_USERNAME: username
      DB_PASSWORD: p455w0rd
      DB_CONNECTION: mysql
      REDIS_HOST: cache
  web:
    #nginx
    image: shakyshane/laravel-web
    volumes:
      - "${LE_DIR}:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
  database:
    #database
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: wh00pwh00p
    ports:
      - "3306:3306"
  cache:
    # redis
    image: redis:3.0-alpine
volumes:
  dbdata:
